In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

%matplotlib inline

In [7]:
df=pd.read_csv('TRAIN.csv')

In [8]:
df.head()

,F01,F02,F03,F04,F05,F06,F07,F08,F09,F10,...,F39,F40,F41,F42,F43,F44,F45,F46,F47,Class
0,0.185570,0.004568,0.005362,0.003335,0.005415,0.004895,0.012764,0.120138,0.140450,3.361753,...,0.041526,-0.230857,0.003310,0.042250,0.005975,0.002104,0.013878,0.001518,0.011347,0
1,0.369536,0.003983,0.003386,0.004902,0.007570,0.012136,0.118050,0.323925,0.132093,2.766117,...,-0.141285,-6.222857,0.834177,0.227968,0.018463,-0.020487,0.001246,0.007489,0.008724,1
2,0.602510,0.008442,0.012961,0.012870,0.046885,0.115401,0.065688,0.306677,0.498805,4.521201,...,0.011334,10.335251,-0.276614,-0.198900,-0.012756,0.014286,-0.001866,0.002687,0.013452,1
3,0.347957,0.064721,0.013611,0.011541,0.006492,0.008690,0.013192,0.164553,0.298665,3.170847,...,0.190479,2.864912,-1.921939,0.891690,1.108098,0.635431,0.081368,-0.000225,0.009166,0
4,0.233653,0.012217,0.010088,0.022095,0.026040,0.015062,0.016063,0.084648,0.213367,8.150943,...,0.203164,0.001812,-0.092731,0.005280,-0.213985,0.032195,0.002081,0.028930,-0.025912,1

In [4]:
df.columns

Index(['F01', 'F02', 'F03', 'F04', 'F05', 'F06', 'F07', 'F08', 'F09', 'F10',
       'F11', 'F12', 'F13', 'F14', 'F15', 'F16', 'F17', 'F18', 'F19', 'F20',
       'F21', 'F22', 'F23', 'F24', 'F25', 'F26', 'F27', 'F28', 'F29', 'F30',
       'F31', 'F32', 'F33', 'F34', 'F35', 'F36', 'F37', 'F38', 'F39', 'F40',
       'F41', 'F42', 'F43', 'F44', 'F45', 'F46', 'F47', 'Class'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43776 entries, 0 to 43775
Data columns (total 48 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   F01     43776 non-null  float64
 1   F02     43776 non-null  float64
 2   F03     43776 non-null  float64
 3   F04     43776 non-null  float64
 4   F05     43776 non-null  float64
 5   F06     43776 non-null  float64
 6   F07     43776 non-null  float64
 7   F08     43776 non-null  float64
 8   F09     43776 non-null  float64
 9   F10     43776 non-null  float64
 10  F11     43776 non-null  float64
 11  F12     43776 non-null  float64
 12  F13     43776 non-null  float64
 13  F14     43776 non-null  float64
 14  F15     43776 non-null  float64
 15  F16     43776 non-null  float64
 16  F17     43776 non-null  float64
 17  F18     43776 non-null  float64
 18  F19     43776 non-null  float64
 19  F20     43776 non-null  float64
 20  F21     43776 non-null  float64
 21  F22     43776 non-null  float64
 22  F23     43776 non-null  float64
 23  F24     43776 non-null  float64
 24  F25     43776 non-null  float64
 25  F26     43776 non-null  float64
 26  F27     43776 non-null  float64
 27  F28     43776 non-null  float64
 28  F29     43776 non-null  float64
 29  F30     43776 non-null  float64
 30  F31     43776 non-null  float64
 31  F32     43776 non-null  float64
 32  F33     43776 non-null  float64
 33  F34     43776 non-null  float64
 34  F35     43776 non-null  float64
 35  F36     43776 non-null  float64
 36  F37     43776 non-null  float64
 37  F38     43776 non-null  float64
 38  F39     43776 non-null  float64
 39  F40     43776 non-null  float64
 40  F41     43776 non-null  float64
 41  F42     43776 non-null  float64
 42  F43     43776 non-null  float64
 43  F44     43776 non-null  float64
 44  F45     43776 non-null  float64
 45  F46     43776 non-null  float64
 46  F47     43776 non-null  float64
 47  Class   43776 non-null  int64
dtypes: float64(47), int64(1)
memory usage: 16.0 MB

In [6]:
df.shape

(43776, 48)

In [7]:
df.isnull().sum()

F01      0
F02      0
F03      0
F04      0
F05      0
F06      0
F07      0
F08      0
F09      0
F10      0
F11      0
F12      0
F13      0
F14      0
F15      0
F16      0
F17      0
F18      0
F19      0
F20      0
F21      0
F22      0
F23      0
F24      0
F25      0
F26      0
F27      0
F28      0
F29      0
F30      0
F31      0
F32      0
F33      0
F34      0
F35      0
F36      0
F37      0
F38      0
F39      0
F40      0
F41      0
F42      0
F43      0
F44      0
F45      0
F46      0
F47      0
Class    0
dtype: int64

In [9]:
# checking duplicated
df.duplicated().sum()

np.int64(738)

In [10]:
# removing duplicated
df.drop_duplicates(inplace=True)

In [11]:
df['Class'].value_counts()

Class
0    25727
1    17311
Name: count, dtype: int64

In [12]:
X=df.drop("Class", axis=1)
y=df['Class']

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

print("Accuracy:", accuracy_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))
print(classification_report(y_test, y_pred))

Accuracy: 0.7280049566294919
ROC-AUC: 0.730966600502713
              precision    recall  f1-score   support

           0       0.71      0.93      0.80      7712
           1       0.81      0.42      0.56      5200

    accuracy                           0.73     12912
   macro avg       0.76      0.68      0.68     12912
weighted avg       0.75      0.73      0.70     12912

In [33]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score, classification_report, accuracy_score

rf = RandomForestClassifier(
    n_estimators=300,
    class_weight="balanced",
    n_jobs=-1,
    random_state=42
)

rf.fit(X_train, y_train)

y_proba = rf.predict_proba(X_test)[:, 1]

print("ROC-AUC:", roc_auc_score(y_test, y_proba))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, rf.predict(X_test)))

ROC-AUC: 0.9988221153846154
Accuracy: 0.9836586121437423

Classification Report:

              precision    recall  f1-score   support

           0       0.97      1.00      0.98      7712
           1       0.99      0.96      0.98      5200

    accuracy                           0.98     12912
   macro avg       0.98      0.98      0.98     12912
weighted avg       0.98      0.98      0.98     12912

In [32]:
import xgboost as xgb
from sklearn.metrics import roc_auc_score, classification_report, accuracy_score

model = xgb.XGBClassifier(
    eval_metric="auc",
    n_estimators=300,
    learning_rate=0.1,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    n_jobs=-1,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:, 1]

print("ROC-AUC:", roc_auc_score(y_test, y_proba))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, model.predict(X_test)))

ROC-AUC: 0.9983588264044048
Accuracy: 0.9836586121437423

Classification Report:

              precision    recall  f1-score   support

           0       0.98      0.99      0.99      7712
           1       0.99      0.97      0.98      5200

    accuracy                           0.98     12912
   macro avg       0.98      0.98      0.98     12912
weighted avg       0.98      0.98      0.98     12912

In [34]:
import joblib

joblib.dump(rf, "../models/random_forest_model.pkl")

['random_forest_model.pkl']

In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
import numpy as np

rf = RandomForestClassifier(
    class_weight="balanced",
    n_jobs=-1,
    random_state=42
)

param_dist = {
    "n_estimators": [200, 300, 400],
    "max_depth": [10, 20, None],      # biggest speed gain
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": ["sqrt", 0.5],
    "bootstrap": [True]
}

rf_search = RandomizedSearchCV(
    rf,
    param_distributions=param_dist,
    n_iter=15,        # cut in half
    cv=3,
    scoring="roc_auc",
    verbose=2,
    n_jobs=-1,
    random_state=42
)

rf_search.fit(X_train, y_train)

Fitting 3 folds for each of 15 candidates, totalling 45 fits

RandomizedSearchCV(cv=3,
                   estimator=RandomForestClassifier(class_weight='balanced',
                                                    n_jobs=-1,
                                                    random_state=42),
                   n_iter=15, n_jobs=-1,
                   param_distributions={'bootstrap': [True],
                                        'max_depth': [10, 20, None],
                                        'max_features': ['sqrt', 0.5],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [200, 300, 400]},
                   random_state=42, scoring='roc_auc', verbose=2)

In [18]:
from sklearn.metrics import roc_auc_score, classification_report, accuracy_score

best_rf = rf_search.best_estimator_

print("Best RF params:", rf_search.best_params_)
print("Best CV ROC-AUC:", rf_search.best_score_)

rf_auc = roc_auc_score(y_test, best_rf.predict_proba(X_test)[:, 1])
print("Test ROC-AUC:", rf_auc)

y_pred=best_rf.predict(X_test)

print(accuracy_score(y_test, y_pred))

Best RF params: {'n_estimators': 300, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': None, 'bootstrap': True}
Best CV ROC-AUC: 0.9982835086853763
Test ROC-AUC: 0.9988221153846154
0.9810254027261462

In [19]:
# storing best_rf model in pkl file

import joblib
joblib.dump(best_rf, "best_random_forest_model.pkl")

['best_random_forest_model.pkl']

In [20]:
output_df=pd.read_csv("TEST.csv")

In [21]:
output_df.head()

,ID,F01,F02,F03,F04,F05,F06,F07,F08,F09,...,F38,F39,F40,F41,F42,F43,F44,F45,F46,F47
0,1,0.277497,0.011515,0.009359,0.011706,0.015613,0.063679,0.021114,0.152000,0.220904,...,2.974426,0.009399,0.015668,0.001999,-0.000937,0.010605,-0.001117,0.043216,-0.000077,-0.040124
1,2,0.158754,0.013861,0.020935,0.002451,0.005939,0.006830,0.006934,0.117209,0.103432,...,2.619811,0.029324,-0.003211,0.037691,-0.083697,0.006595,0.044507,0.007523,-0.000283,-0.007837
2,3,0.504418,0.009106,0.007395,0.009073,0.029486,0.086782,0.122499,0.179376,0.445695,...,4.411972,-0.171520,-0.866895,-0.070657,0.034070,-0.000493,-0.011417,-0.004844,-0.034235,-0.001832
3,4,0.556345,0.005370,0.005670,0.005167,0.013731,0.014570,0.014776,0.522296,0.189882,...,2.709162,0.044236,19.880789,-2.144453,-1.792552,-0.034137,-0.051971,-0.085069,-0.000110,0.045889
4,5,0.128356,0.010014,0.016144,0.003891,0.004472,0.005297,0.007538,0.075874,0.101176,...,2.872020,-0.056908,0.006535,0.070059,-0.007989,0.004089,-0.000206,-0.011331,0.000441,-0.025263

In [22]:
output_df.shape

(10944, 48)

In [23]:
output_df.isnull().sum()

ID     0
F01    0
F02    0
F03    0
F04    0
F05    0
F06    0
F07    0
F08    0
F09    0
F10    0
F11    0
F12    0
F13    0
F14    0
F15    0
F16    0
F17    0
F18    0
F19    0
F20    0
F21    0
F22    0
F23    0
F24    0
F25    0
F26    0
F27    0
F28    0
F29    0
F30    0
F31    0
F32    0
F33    0
F34    0
F35    0
F36    0
F37    0
F38    0
F39    0
F40    0
F41    0
F42    0
F43    0
F44    0
F45    0
F46    0
F47    0
dtype: int64

In [24]:
X_output = output_df.drop("ID", axis=1)

In [25]:
y_output=best_rf.predict(X_output)

In [26]:
# concating ID and y_output for output_test.csv

output_test = pd.concat([output_df["ID"], pd.Series(y_output, name="Class")], axis=1)

In [27]:
output_test.head()

   ID  Class
0   1      1
1   2      0
2   3      1
3   4      0
4   5      0

In [28]:
# converting output_test to csv

output_test.to_csv("output_test.csv", index=False)